import 'dart:ui';
import 'front_body_data.dart'; 

const List<BodyPartDefinition> kLateralLeftBodyPartsList = [
  BodyPartDefinition(id: 'parietal', dbId: 1, name: 'Parietal', color: Color(0xff010100)),
  BodyPartDefinition(id: 'frontal', dbId: 2, name: 'Frontal', color: Color(0xff020200)),
  BodyPartDefinition(id: 'orbitaria', dbId: 3, name: 'Orbitária', color: Color(0xff030300)),
  BodyPartDefinition(id: 'temporal', dbId: 4, name: 'Temporal', color: Color(0xff040400)),
  BodyPartDefinition(id: 'occipital', dbId: 5, name: 'Occipital', color: Color(0xff050500)),
  BodyPartDefinition(id: 'auricular', dbId: 6, name: 'Auricular', color: Color(0xff060600)),
  BodyPartDefinition(id: 'nasal', dbId: 7, name: 'Nasal', color: Color(0xff070700)),
  BodyPartDefinition(id: 'malar', dbId: 8, name: 'Malar', color: Color(0xff080800)),
  BodyPartDefinition(id: 'zigomatica', dbId: 9, name: 'Zigomática', color: Color(0xff090900)),
  BodyPartDefinition(id: 'masseterina', dbId: 10, name: 'Masseterina', color: Color(0xff101000)),
  BodyPartDefinition(id: 'nuca', dbId: 11, name: 'Nuca', color: Color(0xff111100)),
  BodyPartDefinition(id: 'supra_clavicular', dbId: 12, name: 'Supra-clavicular', color: Color(0xff121200)),
  BodyPartDefinition(id: 'carotidiana', dbId: 13, name: 'Carotidiana', color: Color(0xff131300)),
  BodyPartDefinition(id: 'bucinadora', dbId: 14, name: 'Bucinadora', color: Color(0xff141400)),
  BodyPartDefinition(id: 'labial', dbId: 15, name: 'Labial', color: Color(0xff151500)),
  BodyPartDefinition(id: 'mentoniana', dbId: 16, name: 'Mentoniana', color: Color(0xff161600)),
  BodyPartDefinition(id: 'supra_hioideia', dbId: 17, name: 'Supra-hioideia', color: Color(0xff171700)),
  BodyPartDefinition(id: 'infra_hioideia', dbId: 18, name: 'Infra-Hioideia', color: Color(0xff181800)),
  BodyPartDefinition(id: 'escapulo_umeral', dbId: 19, name: 'Escapulo-Umeral', color: Color(0xff191900)),
  BodyPartDefinition(id: 'clavicular', dbId: 20, name: 'Clavicular', color: Color(0xff202000)),
  BodyPartDefinition(id: 'infra_clavicular', dbId: 21, name: 'Infra-Clavicular', color: Color(0xff212100)),
  BodyPartDefinition(id: 'hemitorax', dbId: 22, name: 'Hemitorax', color: Color(0xff222200)),
  BodyPartDefinition(id: 'esternal', dbId: 23, name: 'Esternal', color: Color(0xff232300)),
  BodyPartDefinition(id: 'deltoidiana', dbId: 24, name: 'Deltoidiana', color: Color(0xff242400)),
  BodyPartDefinition(id: 'braco_terco_sup', dbId: 25, name: 'Terço Superior do Braço', color: Color(0xff252500)),
  BodyPartDefinition(id: 'braco_terco_med', dbId: 26, name: 'Terço Médio do Braço', color: Color(0xff262600)),
  BodyPartDefinition(id: 'braco_terco_inf', dbId: 27, name: 'Terço Inferior do Braço', color: Color(0xff272700)),
  BodyPartDefinition(id: 'lateral_cotovelo', dbId: 28, name: 'Lateral do Cotovelo', color: Color(0xff282800)),
  BodyPartDefinition(id: 'cotovelo', dbId: 29, name: 'Cotovelo', color: Color(0xff292900)),
  BodyPartDefinition(id: 'antebraco_terco_sup', dbId: 30, name: 'Terço Superior do Antebraço', color: Color(0xff303000)),
  BodyPartDefinition(id: 'antebraco_terco_med', dbId: 31, name: 'Terço Médio do Antebraço', color: Color(0xff313100)),
  BodyPartDefinition(id: 'antebraco_terco_inf', dbId: 32, name: 'Terço Inferior do Antebraço', color: Color(0xff323200)),
  BodyPartDefinition(id: 'punho', dbId: 33, name: 'Punho', color: Color(0xff333300)),
  BodyPartDefinition(id: 'dorsal_mao', dbId: 34, name: 'Dorsal da Mão', color: Color(0xff343400)),
  BodyPartDefinition(id: 'palmar_mao', dbId: 35, name: 'Palmar da Mão', color: Color(0xff353500)),
  BodyPartDefinition(id: 'mamaria', dbId: 36, name: 'Mamária', color: Color(0xff363600)),
  BodyPartDefinition(id: 'hipocondrio', dbId: 37, name: 'Hipocôndrio', color: Color(0xff373700)),
  BodyPartDefinition(id: 'epigastrica', dbId: 38, name: 'Epigástrica', color: Color(0xff383800)),
  BodyPartDefinition(id: 'flanco', dbId: 39, name: 'Flanco', color: Color(0xff393900)),
  BodyPartDefinition(id: 'abdominal_mesogastrica', dbId: 40, name: 'Abdominal (Mesogástrica)', color: Color(0xff404000)),
  BodyPartDefinition(id: 'umbilical', dbId: 41, name: 'Umbilical', color: Color(0xff414100)),
  BodyPartDefinition(id: 'hipogastrica', dbId: 42, name: 'Hipogástrica', color: Color(0xff424200)),
  BodyPartDefinition(id: 'pubiana', dbId: 43, name: 'Pubiana', color: Color(0xff434300)),
  BodyPartDefinition(id: 'fossa_iliaca', dbId: 44, name: 'Fossa Ilíaca', color: Color(0xff444400)),
  BodyPartDefinition(id: 'inguinal', dbId: 45, name: 'Inguinal', color: Color(0xff454500)),
  BodyPartDefinition(id: 'crural', dbId: 46, name: 'Crural', color: Color(0xff464600)),
  BodyPartDefinition(id: 'quadril', dbId: 47, name: 'Quadril', color: Color(0xff474700)),
  BodyPartDefinition(id: 'glutea', dbId: 48, name: 'Glútea', color: Color(0xff484800)),
  BodyPartDefinition(id: 'coxa_terco_sup', dbId: 49, name: 'Terço Superior da Coxa', color: Color(0xff494900)),
  BodyPartDefinition(id: 'coxa_terco_med', dbId: 50, name: 'Terço Médio da Coxa', color: Color(0xff505000)),
  BodyPartDefinition(id: 'coxa_terco_inf', dbId: 51, name: 'Terço Inferior da Coxa', color: Color(0xff515100)),
  BodyPartDefinition(id: 'face_lateral_joelho', dbId: 52, name: 'Face Lateral do Joelho', color: Color(0xff525200)),
  BodyPartDefinition(id: 'joelho', dbId: 53, name: 'Joelho', color: Color(0xff535300)),
  BodyPartDefinition(id: 'popliteia', dbId: 54, name: 'Poplitéia', color: Color(0xff545400)),
  BodyPartDefinition(id: 'perna_terco_sup', dbId: 55, name: 'Terço Superior da Perna', color: Color(0xff555500)),
  BodyPartDefinition(id: 'perna_terco_med', dbId: 56, name: 'Terço Médio da Perna', color: Color(0xff565600)),
  BodyPartDefinition(id: 'perna_terco_inf', dbId: 57, name: 'Terço Inferior da Perna', color: Color(0xff575700)),
  BodyPartDefinition(id: 'maleolar', dbId: 58, name: 'Maleolar', color: Color(0xff585800)),
  BodyPartDefinition(id: 'dorsal_pe', dbId: 59, name: 'Dorsal do Pé', color: Color(0xff595900)),
  BodyPartDefinition(id: 'calcaneo', dbId: 60, name: 'Calcâneo', color: Color(0xff606000)),
  BodyPartDefinition(id: 'lateral_pe', dbId: 61, name: 'Lateral do Pé', color: Color(0xff616100)),
  BodyPartDefinition(id: 'artelhos', dbId: 62, name: 'Artelhos', color: Color(0xff626200)),
];

    final Map<int, String> kColorToIdLateralLeftMap = {
  for (var part in kLateralLeftBodyPartsList) part.color.value: part.id,
};

final Map<String, BodyPartDefinition> kIdToDefinitionLateralLeftMap = {
  for (var part in kLateralLeftBodyPartsList) part.id: part,
};